// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: protos/common/collection/collection.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Com_Rivuletkit_Common_Collection_CollectionItemType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case item // = 0
  case folder // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .item
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .item
    case 1: self = .folder
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .item: return 0
    case .folder: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Com_Rivuletkit_Common_Collection_CollectionItemType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Com_Rivuletkit_Common_Collection_CollectionItemType] = [
    .item,
    .folder,
  ]
}

#endif  // swift(>=4.2)

public struct Com_Rivuletkit_Common_Collection_Collection {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var info: Com_Rivuletkit_Common_Collection_CollectionInfo {
    get {return _info ?? Com_Rivuletkit_Common_Collection_CollectionInfo()}
    set {_info = newValue}
  }
  /// Returns true if `info` has been explicitly set.
  public var hasInfo: Bool {return self._info != nil}
  /// Clears the value of `info`. Subsequent reads from it will return its default value.
  public mutating func clearInfo() {self._info = nil}

  public var items: [Com_Rivuletkit_Common_Collection_CollectionItem] = []

  public var events: [Com_Rivuletkit_Common_Collection_CollectionEvent] = []

  public var variables: [Com_Rivuletkit_Common_Collection_CollectionVariable] = []

  public var auth: Com_Rivuletkit_Common_Collection_Auth {
    get {return _auth ?? Com_Rivuletkit_Common_Collection_Auth()}
    set {_auth = newValue}
  }
  /// Returns true if `auth` has been explicitly set.
  public var hasAuth: Bool {return self._auth != nil}
  /// Clears the value of `auth`. Subsequent reads from it will return its default value.
  public mutating func clearAuth() {self._auth = nil}

  public var protocolProfileBehavior: Com_Rivuletkit_Common_Collection_ProtocolProfileBehavior {
    get {return _protocolProfileBehavior ?? Com_Rivuletkit_Common_Collection_ProtocolProfileBehavior()}
    set {_protocolProfileBehavior = newValue}
  }
  /// Returns true if `protocolProfileBehavior` has been explicitly set.
  public var hasProtocolProfileBehavior: Bool {return self._protocolProfileBehavior != nil}
  /// Clears the value of `protocolProfileBehavior`. Subsequent reads from it will return its default value.
  public mutating func clearProtocolProfileBehavior() {self._protocolProfileBehavior = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _info: Com_Rivuletkit_Common_Collection_CollectionInfo? = nil
  fileprivate var _auth: Com_Rivuletkit_Common_Collection_Auth? = nil
  fileprivate var _protocolProfileBehavior: Com_Rivuletkit_Common_Collection_ProtocolProfileBehavior? = nil
}

public struct Com_Rivuletkit_Common_Collection_CollectionInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A collection's friendly name is defined by this field.
  public var name: String = String()

  /// 由于目前校验完整性暂时不实现，故此参数暂设定为可选
  public var schema: String {
    get {return _schema ?? String()}
    set {_schema = newValue}
  }
  /// Returns true if `schema` has been explicitly set.
  public var hasSchema: Bool {return self._schema != nil}
  /// Clears the value of `schema`. Subsequent reads from it will return its default value.
  public mutating func clearSchema() {self._schema = nil}

  public var description_p: String {
    get {return _description_p ?? String()}
    set {_description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {return self._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {self._description_p = nil}

  public var version: String {
    get {return _version ?? String()}
    set {_version = newValue}
  }
  /// Returns true if `version` has been explicitly set.
  public var hasVersion: Bool {return self._version != nil}
  /// Clears the value of `version`. Subsequent reads from it will return its default value.
  public mutating func clearVersion() {self._version = nil}

  /// Every collection is identified by the unique value of this field.
  public var postmanID: String {
    get {return _postmanID ?? String()}
    set {_postmanID = newValue}
  }
  /// Returns true if `postmanID` has been explicitly set.
  public var hasPostmanID: Bool {return self._postmanID != nil}
  /// Clears the value of `postmanID`. Subsequent reads from it will return its default value.
  public mutating func clearPostmanID() {self._postmanID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _schema: String? = nil
  fileprivate var _description_p: String? = nil
  fileprivate var _version: String? = nil
  fileprivate var _postmanID: String? = nil
}

public struct Com_Rivuletkit_Common_Collection_CollectionItem {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// conmmon
  public var type: Com_Rivuletkit_Common_Collection_CollectionItemType = .item

  public var events: [Com_Rivuletkit_Common_Collection_CollectionEvent] = []

  public var variables: [Com_Rivuletkit_Common_Collection_CollectionVariable] = []

  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  public var description_p: String {
    get {return _description_p ?? String()}
    set {_description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {return self._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {self._description_p = nil}

  public var protocolProfileBehavior: Com_Rivuletkit_Common_Collection_ProtocolProfileBehavior {
    get {return _protocolProfileBehavior ?? Com_Rivuletkit_Common_Collection_ProtocolProfileBehavior()}
    set {_protocolProfileBehavior = newValue}
  }
  /// Returns true if `protocolProfileBehavior` has been explicitly set.
  public var hasProtocolProfileBehavior: Bool {return self._protocolProfileBehavior != nil}
  /// Clears the value of `protocolProfileBehavior`. Subsequent reads from it will return its default value.
  public mutating func clearProtocolProfileBehavior() {self._protocolProfileBehavior = nil}

  /// item
  public var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var request: Com_Rivuletkit_Common_Collection_Request {
    get {return _request ?? Com_Rivuletkit_Common_Collection_Request()}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  public var hasRequest: Bool {return self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  public mutating func clearRequest() {self._request = nil}

  public var responses: Com_Rivuletkit_Common_Collection_Response {
    get {return _responses ?? Com_Rivuletkit_Common_Collection_Response()}
    set {_responses = newValue}
  }
  /// Returns true if `responses` has been explicitly set.
  public var hasResponses: Bool {return self._responses != nil}
  /// Clears the value of `responses`. Subsequent reads from it will return its default value.
  public mutating func clearResponses() {self._responses = nil}

  /// folder
  public var items: [Com_Rivuletkit_Common_Collection_CollectionItem] = []

  public var auth: Com_Rivuletkit_Common_Collection_Auth {
    get {return _auth ?? Com_Rivuletkit_Common_Collection_Auth()}
    set {_auth = newValue}
  }
  /// Returns true if `auth` has been explicitly set.
  public var hasAuth: Bool {return self._auth != nil}
  /// Clears the value of `auth`. Subsequent reads from it will return its default value.
  public mutating func clearAuth() {self._auth = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _name: String? = nil
  fileprivate var _description_p: String? = nil
  fileprivate var _protocolProfileBehavior: Com_Rivuletkit_Common_Collection_ProtocolProfileBehavior? = nil
  fileprivate var _id: String? = nil
  fileprivate var _request: Com_Rivuletkit_Common_Collection_Request? = nil
  fileprivate var _responses: Com_Rivuletkit_Common_Collection_Response? = nil
  fileprivate var _auth: Com_Rivuletkit_Common_Collection_Auth? = nil
}

public struct Com_Rivuletkit_Common_Collection_CollectionEvent {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Can be set to `test` or `prerequest` for test scripts or pre-request scripts respectively.
  public var listen: String = String()

  /// A unique identifier for the enclosing event.
  public var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  /// optional Script script = 3; // 保留属性，暂不实现 
  public var disabled: Bool {
    get {return _disabled ?? false}
    set {_disabled = newValue}
  }
  /// Returns true if `disabled` has been explicitly set.
  public var hasDisabled: Bool {return self._disabled != nil}
  /// Clears the value of `disabled`. Subsequent reads from it will return its default value.
  public mutating func clearDisabled() {self._disabled = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: String? = nil
  fileprivate var _disabled: Bool? = nil
}

public struct Com_Rivuletkit_Common_Collection_CollectionVariable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A variable ID is a unique user-defined value that identifies the variable within a collection. In traditional terms, this would be a variable name.
  public var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  /// A variable key is a human friendly value that identifies the variable within a collection. In traditional terms, this would be a variable name.
  public var key: String {
    get {return _key ?? String()}
    set {_key = newValue}
  }
  /// Returns true if `key` has been explicitly set.
  public var hasKey: Bool {return self._key != nil}
  /// Clears the value of `key`. Subsequent reads from it will return its default value.
  public mutating func clearKey() {self._key = nil}

  /// The value that a variable holds in this collection. Ultimately, the variables will be replaced by this value, when say running a set of requests from a collection.
  public var value: String {
    get {return _value ?? String()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {return self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  /// A variable may have multiple types. This field specifies the type of the variable.
  public var type: String {
    get {return _type ?? String()}
    set {_type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  public var hasType: Bool {return self._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  public mutating func clearType() {self._type = nil}

  /// Variable name
  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  public var description_p: String {
    get {return _description_p ?? String()}
    set {_description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {return self._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {self._description_p = nil}

  /// boolean default false
  public var system: Bool {
    get {return _system ?? false}
    set {_system = newValue}
  }
  /// Returns true if `system` has been explicitly set.
  public var hasSystem: Bool {return self._system != nil}
  /// Clears the value of `system`. Subsequent reads from it will return its default value.
  public mutating func clearSystem() {self._system = nil}

  /// boolean default false
  public var disabled: Bool {
    get {return _disabled ?? false}
    set {_disabled = newValue}
  }
  /// Returns true if `disabled` has been explicitly set.
  public var hasDisabled: Bool {return self._disabled != nil}
  /// Clears the value of `disabled`. Subsequent reads from it will return its default value.
  public mutating func clearDisabled() {self._disabled = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: String? = nil
  fileprivate var _key: String? = nil
  fileprivate var _value: String? = nil
  fileprivate var _type: String? = nil
  fileprivate var _name: String? = nil
  fileprivate var _description_p: String? = nil
  fileprivate var _system: Bool? = nil
  fileprivate var _disabled: Bool? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Com_Rivuletkit_Common_Collection_CollectionItemType: @unchecked Sendable {}
extension Com_Rivuletkit_Common_Collection_Collection: @unchecked Sendable {}
extension Com_Rivuletkit_Common_Collection_CollectionInfo: @unchecked Sendable {}
extension Com_Rivuletkit_Common_Collection_CollectionItem: @unchecked Sendable {}
extension Com_Rivuletkit_Common_Collection_CollectionEvent: @unchecked Sendable {}
extension Com_Rivuletkit_Common_Collection_CollectionVariable: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "com.rivuletkit.common.collection"

extension Com_Rivuletkit_Common_Collection_CollectionItemType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ITEM"),
    1: .same(proto: "FOLDER"),
  ]
}

extension Com_Rivuletkit_Common_Collection_Collection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Collection"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "info"),
    2: .same(proto: "items"),
    3: .same(proto: "events"),
    4: .same(proto: "variables"),
    5: .same(proto: "auth"),
    6: .same(proto: "protocolProfileBehavior"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._info) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.events) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.variables) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._auth) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._protocolProfileBehavior) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._info {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 2)
    }
    if !self.events.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.events, fieldNumber: 3)
    }
    if !self.variables.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.variables, fieldNumber: 4)
    }
    try { if let v = self._auth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._protocolProfileBehavior {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Com_Rivuletkit_Common_Collection_Collection, rhs: Com_Rivuletkit_Common_Collection_Collection) -> Bool {
    if lhs._info != rhs._info {return false}
    if lhs.items != rhs.items {return false}
    if lhs.events != rhs.events {return false}
    if lhs.variables != rhs.variables {return false}
    if lhs._auth != rhs._auth {return false}
    if lhs._protocolProfileBehavior != rhs._protocolProfileBehavior {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Com_Rivuletkit_Common_Collection_CollectionInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CollectionInfo"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "schema"),
    3: .same(proto: "description"),
    4: .same(proto: "version"),
    5: .standard(proto: "_postman_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._schema) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._version) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._postmanID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._schema {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._version {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._postmanID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Com_Rivuletkit_Common_Collection_CollectionInfo, rhs: Com_Rivuletkit_Common_Collection_CollectionInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._schema != rhs._schema {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs._version != rhs._version {return false}
    if lhs._postmanID != rhs._postmanID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Com_Rivuletkit_Common_Collection_CollectionItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CollectionItem"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "events"),
    3: .same(proto: "variables"),
    4: .same(proto: "name"),
    5: .same(proto: "description"),
    6: .same(proto: "protocolProfileBehavior"),
    7: .same(proto: "id"),
    8: .same(proto: "request"),
    9: .same(proto: "responses"),
    10: .same(proto: "items"),
    11: .same(proto: "auth"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.events) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.variables) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._protocolProfileBehavior) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._request) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._responses) }()
      case 10: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      case 11: try { try decoder.decodeSingularMessageField(value: &self._auth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.type != .item {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    if !self.events.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.events, fieldNumber: 2)
    }
    if !self.variables.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.variables, fieldNumber: 3)
    }
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._protocolProfileBehavior {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._request {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._responses {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 10)
    }
    try { if let v = self._auth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Com_Rivuletkit_Common_Collection_CollectionItem, rhs: Com_Rivuletkit_Common_Collection_CollectionItem) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.events != rhs.events {return false}
    if lhs.variables != rhs.variables {return false}
    if lhs._name != rhs._name {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs._protocolProfileBehavior != rhs._protocolProfileBehavior {return false}
    if lhs._id != rhs._id {return false}
    if lhs._request != rhs._request {return false}
    if lhs._responses != rhs._responses {return false}
    if lhs.items != rhs.items {return false}
    if lhs._auth != rhs._auth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Com_Rivuletkit_Common_Collection_CollectionEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CollectionEvent"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "listen"),
    2: .same(proto: "id"),
    4: .same(proto: "disabled"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.listen) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._disabled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.listen.isEmpty {
      try visitor.visitSingularStringField(value: self.listen, fieldNumber: 1)
    }
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._disabled {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Com_Rivuletkit_Common_Collection_CollectionEvent, rhs: Com_Rivuletkit_Common_Collection_CollectionEvent) -> Bool {
    if lhs.listen != rhs.listen {return false}
    if lhs._id != rhs._id {return false}
    if lhs._disabled != rhs._disabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Com_Rivuletkit_Common_Collection_CollectionVariable: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CollectionVariable"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "key"),
    3: .same(proto: "value"),
    4: .same(proto: "type"),
    5: .same(proto: "name"),
    6: .same(proto: "description"),
    7: .same(proto: "system"),
    8: .same(proto: "disabled"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._key) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._value) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._type) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._system) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self._disabled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._key {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._value {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._type {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._system {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._disabled {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Com_Rivuletkit_Common_Collection_CollectionVariable, rhs: Com_Rivuletkit_Common_Collection_CollectionVariable) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._key != rhs._key {return false}
    if lhs._value != rhs._value {return false}
    if lhs._type != rhs._type {return false}
    if lhs._name != rhs._name {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs._system != rhs._system {return false}
    if lhs._disabled != rhs._disabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
